export { employeesApi, toQuery } from './employees.api';
export {
  EMPLOYEE_KEYS,
  useChangeDepartment,
  useChangeDesignation,
  useChangeManager,
  useChangeStatus,
  useCreateEmployee,
  useCreateSalary,
  useDecideSalary,
  useDepartments,
  useDesignations,
  useEmployee,
  useEmployeeAudit,
  useEmployeeHistory,
  useEmployeeMeta,
  useEmployees,
  useEmployeeSalary,
  useLabourPresence,
  useLabourPresenceAudit,
  useLabourStrength,
  useLabourStrengthAudit,
  useOrgTree,
  usePromote,
  useRecordLabourPresence,
  useReporting,
  useRetireDepartment,
  useRetireDesignation,
  useSalaryApprovals,
  useSalaryRevisions,
  useSaveDepartment,
  useSaveDesignation,
  useSetLabourStrength,
  useUpdateEmployee,
  useWorkforceReports,
} from './employees.queries';
