export { default as QCDashboardPage } from './QCDashboardPage'
export { default as PendingInspectionsPage } from './PendingInspectionsPage'
export { default as InspectionDetailPage } from './InspectionDetailPage'
export { default as ApprovalQueuePage } from './ApprovalQueuePage'
export * from './masterdata'
