export const MAINTENANCE_MODULE_PREFIX = 'maintenance';

export const MAINTENANCE_PERMISSIONS = {
  VIEW_MODULE: 'maintenance.can_view_maintenance_module',
  VIEW_DASHBOARD: 'maintenance.can_view_maintenance_dashboard',
  MANAGE_SETTINGS: 'maintenance.can_manage_maintenance_settings',
  VIEW_ASSET: 'maintenance.view_asset',
  CREATE_ASSET: 'maintenance.add_asset',
  EDIT_ASSET: 'maintenance.change_asset',
  DELETE_ASSET: 'maintenance.delete_asset',
  DEACTIVATE_ASSET: 'maintenance.can_deactivate_asset',
  VIEW_ASSET_CATEGORY: 'maintenance.view_assetcategory',
  CREATE_ASSET_CATEGORY: 'maintenance.add_assetcategory',
  EDIT_ASSET_CATEGORY: 'maintenance.change_assetcategory',
  VIEW_ASSET_LOCATION: 'maintenance.view_assetlocation',
  CREATE_ASSET_LOCATION: 'maintenance.add_assetlocation',
  EDIT_ASSET_LOCATION: 'maintenance.change_assetlocation',
  VIEW_ASSET_DEPARTMENT: 'maintenance.view_assetdepartment',
  CREATE_ASSET_DEPARTMENT: 'maintenance.add_assetdepartment',
  EDIT_ASSET_DEPARTMENT: 'maintenance.change_assetdepartment',
  VIEW_ASSET_PHOTO: 'maintenance.view_assetphoto',
  CREATE_ASSET_PHOTO: 'maintenance.add_assetphoto',
  EDIT_ASSET_PHOTO: 'maintenance.change_assetphoto',
  VIEW_ASSET_DOCUMENT: 'maintenance.view_assetdocument',
  CREATE_ASSET_DOCUMENT: 'maintenance.add_assetdocument',
  EDIT_ASSET_DOCUMENT: 'maintenance.change_assetdocument',
  VIEW_WORK_ORDER: 'maintenance.can_view_work_order',
  MANAGE_WORK_ORDER: 'maintenance.can_manage_work_order',
  CREATE_WORK_ORDER: 'maintenance.can_create_work_order',
  ASSIGN_WORK_ORDER: 'maintenance.can_assign_work_order',
  START_WORK_ORDER: 'maintenance.can_start_work_order',
  COMPLETE_WORK_ORDER: 'maintenance.can_complete_work_order',
  APPROVE_WORK_ORDER: 'maintenance.can_approve_work_order',
  CLOSE_WORK_ORDER: 'maintenance.can_close_work_order',
  VIEW_MAINTENANCE_WORK_ORDER: 'maintenance.view_maintenanceworkorder',
  CREATE_MAINTENANCE_WORK_ORDER: 'maintenance.add_maintenanceworkorder',
  EDIT_MAINTENANCE_WORK_ORDER: 'maintenance.change_maintenanceworkorder',
  VIEW_WORK_ORDER_PHOTO: 'maintenance.view_maintenanceworkorderphoto',
  CREATE_WORK_ORDER_PHOTO: 'maintenance.add_maintenanceworkorderphoto',
  EDIT_WORK_ORDER_PHOTO: 'maintenance.change_maintenanceworkorderphoto',
  VIEW_PM: 'maintenance.can_view_pm',
  MANAGE_PM: 'maintenance.can_manage_pm',
  VIEW_SPARE: 'maintenance.can_view_spare',
  MANAGE_SPARE: 'maintenance.can_manage_spare',
  REQUEST_SPARE: 'maintenance.add_sparerequest',
  VIEW_FIRE: 'maintenance.can_view_fire',
  MANAGE_FIRE: 'maintenance.can_manage_fire',
  REQUEST_FIRE: 'maintenance.add_firerequest',
  VIEW_FIRE_REPORT: 'maintenance.can_view_fire_report',
  MANAGE_FIRE_REPORT: 'maintenance.can_manage_fire_report',
  REVIEW_FIRE_REPORT: 'maintenance.can_review_fire_report',
  VIEW_FIRE_ISSUE: 'maintenance.can_view_fire_issue',
  MANAGE_FIRE_ISSUE: 'maintenance.can_manage_fire_issue',
  VIEW_SAFETY_FINE: 'maintenance.can_view_safety_fine',
  MANAGE_SAFETY_FINE: 'maintenance.can_manage_safety_fine',
  VIEW_MATERIAL_INDENT: 'maintenance.can_view_material_indent',
  MANAGE_MATERIAL_INDENT: 'maintenance.can_manage_material_indent',
  REVIEW_MATERIAL_INDENT: 'maintenance.can_review_material_indent',
  APPROVE_MATERIAL_INDENT: 'maintenance.can_approve_material_indent',
  PURCHASE_MATERIAL_INDENT: 'maintenance.can_purchase_material_indent',
  GATEIN_MATERIAL_INDENT: 'maintenance.can_gatein_material_indent',
  RECEIVE_MATERIAL_INDENT: 'maintenance.can_receive_material_indent',
  VIEW_WORK_PERMIT: 'maintenance.can_view_work_permit',
  MANAGE_WORK_PERMIT: 'maintenance.can_manage_work_permit',
  ISSUE_WORK_PERMIT: 'maintenance.can_issue_work_permit',
  APPROVE_WORK_PERMIT: 'maintenance.can_approve_work_permit',
  ACCEPT_WORK_PERMIT: 'maintenance.can_accept_work_permit',
  CLOSE_WORK_PERMIT: 'maintenance.can_close_work_permit',
  VIEW_VENDOR: 'maintenance.can_view_vendor',
  MANAGE_VENDOR: 'maintenance.can_manage_vendor',
  VIEW_REPORTS: 'maintenance.can_view_maintenance_reports',
} as const;

export type MaintenancePermission =
  (typeof MAINTENANCE_PERMISSIONS)[keyof typeof MAINTENANCE_PERMISSIONS];
