export const MAINTENANCE_MODULE_PREFIX = 'maintenance';

export const MAINTENANCE_PERMISSIONS = {
  VIEW_MODULE: 'maintenance.can_view_maintenance_module',
  VIEW_DASHBOARD: 'maintenance.can_view_maintenance_dashboard',
  MANAGE_SETTINGS: 'maintenance.can_manage_maintenance_settings',
  VIEW_ASSET: 'maintenance.view_asset',
  CREATE_ASSET: 'maintenance.add_asset',
  EDIT_ASSET: 'maintenance.change_asset',
  DELETE_ASSET: 'maintenance.delete_asset',
  DEACTIVATE_ASSET: 'maintenance.can_deactivate_asset',
  VIEW_ASSET_CATEGORY: 'maintenance.view_assetcategory',
  CREATE_ASSET_CATEGORY: 'maintenance.add_assetcategory',
  EDIT_ASSET_CATEGORY: 'maintenance.change_assetcategory',
  VIEW_ASSET_LOCATION: 'maintenance.view_assetlocation',
  CREATE_ASSET_LOCATION: 'maintenance.add_assetlocation',
  EDIT_ASSET_LOCATION: 'maintenance.change_assetlocation',
  VIEW_ASSET_DEPARTMENT: 'maintenance.view_assetdepartment',
  CREATE_ASSET_DEPARTMENT: 'maintenance.add_assetdepartment',
  EDIT_ASSET_DEPARTMENT: 'maintenance.change_assetdepartment',
  VIEW_ASSET_PHOTO: 'maintenance.view_assetphoto',
  CREATE_ASSET_PHOTO: 'maintenance.add_assetphoto',
  EDIT_ASSET_PHOTO: 'maintenance.change_assetphoto',
  VIEW_ASSET_DOCUMENT: 'maintenance.view_assetdocument',
  CREATE_ASSET_DOCUMENT: 'maintenance.add_assetdocument',
  EDIT_ASSET_DOCUMENT: 'maintenance.change_assetdocument',
  VIEW_WORK_ORDER: 'maintenance.can_view_work_order',
  MANAGE_WORK_ORDER: 'maintenance.can_manage_work_order',
  CREATE_WORK_ORDER: 'maintenance.can_create_work_order',
  ASSIGN_WORK_ORDER: 'maintenance.can_assign_work_order',
  START_WORK_ORDER: 'maintenance.can_start_work_order',
  COMPLETE_WORK_ORDER: 'maintenance.can_complete_work_order',
  APPROVE_WORK_ORDER: 'maintenance.can_approve_work_order',
  CLOSE_WORK_ORDER: 'maintenance.can_close_work_order',
  VIEW_MAINTENANCE_WORK_ORDER: 'maintenance.view_maintenanceworkorder',
  CREATE_MAINTENANCE_WORK_ORDER: 'maintenance.add_maintenanceworkorder',
  EDIT_MAINTENANCE_WORK_ORDER: 'maintenance.change_maintenanceworkorder',
  VIEW_WORK_ORDER_PHOTO: 'maintenance.view_maintenanceworkorderphoto',
  CREATE_WORK_ORDER_PHOTO: 'maintenance.add_maintenanceworkorderphoto',
  EDIT_WORK_ORDER_PHOTO: 'maintenance.change_maintenanceworkorderphoto',
  VIEW_WORK_ORDER_ATTACHMENT: 'maintenance.view_maintenanceworkorderattachment',
  CREATE_WORK_ORDER_ATTACHMENT: 'maintenance.add_maintenanceworkorderattachment',
  EDIT_WORK_ORDER_ATTACHMENT: 'maintenance.change_maintenanceworkorderattachment',
  DELETE_WORK_ORDER_ATTACHMENT: 'maintenance.delete_maintenanceworkorderattachment',
  VIEW_PM: 'maintenance.can_view_pm',
  MANAGE_PM: 'maintenance.can_manage_pm',
  VIEW_SPARE: 'maintenance.can_view_spare',
  MANAGE_SPARE: 'maintenance.can_manage_spare',
  REQUEST_SPARE: 'maintenance.add_sparerequest',
  VIEW_FIRE: 'maintenance.can_view_fire',
  MANAGE_FIRE: 'maintenance.can_manage_fire',
  REQUEST_FIRE: 'maintenance.add_firerequest',
  VIEW_FIRE_REPORT: 'maintenance.can_view_fire_report',
  MANAGE_FIRE_REPORT: 'maintenance.can_manage_fire_report',
  REVIEW_FIRE_REPORT: 'maintenance.can_review_fire_report',
  VIEW_FIRE_ISSUE: 'maintenance.can_view_fire_issue',
  MANAGE_FIRE_ISSUE: 'maintenance.can_manage_fire_issue',
  VIEW_SAFETY_FINE: 'maintenance.can_view_safety_fine',
  MANAGE_SAFETY_FINE: 'maintenance.can_manage_safety_fine',
  VIEW_MATERIAL_INDENT: 'maintenance.can_view_material_indent',
  // Legacy superset — grants both drafting and sending for approval.
  MANAGE_MATERIAL_INDENT: 'maintenance.can_manage_material_indent',
  /** Draft-only: raise and edit an indent, no "Send for Approval" */
  DRAFT_MATERIAL_INDENT: 'maintenance.can_draft_material_indent',
  /** Send a parked draft for purchase approval */
  SUBMIT_MATERIAL_INDENT: 'maintenance.can_submit_material_indent',
  REVIEW_MATERIAL_INDENT: 'maintenance.can_review_material_indent',
  APPROVE_MATERIAL_INDENT: 'maintenance.can_approve_material_indent',
  PURCHASE_MATERIAL_INDENT: 'maintenance.can_purchase_material_indent',
  GATEIN_MATERIAL_INDENT: 'maintenance.can_gatein_material_indent',
  RECEIVE_MATERIAL_INDENT: 'maintenance.can_receive_material_indent',
  VIEW_WORK_PERMIT: 'maintenance.can_view_work_permit',
  MANAGE_WORK_PERMIT: 'maintenance.can_manage_work_permit',
  ISSUE_WORK_PERMIT: 'maintenance.can_issue_work_permit',
  APPROVE_WORK_PERMIT: 'maintenance.can_approve_work_permit',
  ACCEPT_WORK_PERMIT: 'maintenance.can_accept_work_permit',
  CLOSE_WORK_PERMIT: 'maintenance.can_close_work_permit',
  VIEW_VENDOR: 'maintenance.can_view_vendor',
  MANAGE_VENDOR: 'maintenance.can_manage_vendor',
  VIEW_REPORTS: 'maintenance.can_view_maintenance_reports',
  VIEW_DAILY_ELECTRICITY: 'maintenance.can_view_daily_electricity',
  // Legacy superset — still grants every electricity right below.
  MANAGE_DAILY_ELECTRICITY: 'maintenance.can_manage_daily_electricity',
  VIEW_ELECTRICITY_METER: 'maintenance.can_view_electricity_meter',
  MANAGE_ELECTRICITY_METER: 'maintenance.can_manage_electricity_meter',
  ADD_DAILY_ELECTRICITY: 'maintenance.can_add_daily_electricity',
  EDIT_DAILY_ELECTRICITY: 'maintenance.can_edit_daily_electricity',
  DELETE_DAILY_ELECTRICITY: 'maintenance.can_delete_daily_electricity',
  VIEW_DAILY_WASTAGE: 'maintenance.can_view_daily_wastage',
  MANAGE_DAILY_WASTAGE: 'maintenance.can_manage_daily_wastage',
} as const;

export type MaintenancePermission =
  (typeof MAINTENANCE_PERMISSIONS)[keyof typeof MAINTENANCE_PERMISSIONS];

/**
 * Any-of gate for the Daily Electricity page: holding any single electricity
 * right (meter master, data entry, correction, delete, plain view) must open the
 * page — the page itself then hides the actions that right does not cover.
 */
export const DAILY_ELECTRICITY_ACCESS_PERMISSIONS = [
  MAINTENANCE_PERMISSIONS.VIEW_DAILY_ELECTRICITY,
  MAINTENANCE_PERMISSIONS.MANAGE_DAILY_ELECTRICITY,
  MAINTENANCE_PERMISSIONS.VIEW_ELECTRICITY_METER,
  MAINTENANCE_PERMISSIONS.MANAGE_ELECTRICITY_METER,
  MAINTENANCE_PERMISSIONS.ADD_DAILY_ELECTRICITY,
  MAINTENANCE_PERMISSIONS.EDIT_DAILY_ELECTRICITY,
  MAINTENANCE_PERMISSIONS.DELETE_DAILY_ELECTRICITY,
] as const;
