import type { LucideIcon } from 'lucide-react';
import {
  Boxes,
  Building2,
  Factory,
  HardHat,
  LogIn,
  LogOut,
  Package,
  PackageOpen,
  PackageX,
  RotateCcw,
  Send,
  Truck,
  Undo2,
  UserMinus,
  UserPlus,
  UtensilsCrossed,
  Wrench,
} from 'lucide-react';

import { GATE_PERMISSIONS } from '@/config/permissions';

export type GateEntryDirection = 'in' | 'out' | 'return';
export type GateVehicleMode = 'vehicle' | 'non_vehicle';

export interface GateEntryTypeConfig {
  id: string;
  title: string;
  description: string;
  direction: GateEntryDirection;
  vehicleMode: GateVehicleMode;
  dashboardRoute: string;
  newEntryRoute: string;
  viewPermissions: readonly string[];
  createPermissions: readonly string[];
  icon: LucideIcon;
  colorClassName: string;
  keywords: readonly string[];
  requiresWeighment?: boolean;
  requiresGatepass?: boolean;
  /**
   * Hide from the "New Entry" picker. For flows the gate acts on but does not
   * originate — a returnable gate pass is raised by a department, and the gate
   * only works its queue.
   */
  hideFromNewEntry?: boolean;
}

export const GATE_ENTRY_TYPES: GateEntryTypeConfig[] = [
  {
    id: 'raw-materials',
    title: 'Raw Materials (RM/PM/Assets)',
    description: 'Purchase material, packing material, and asset inward entries.',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/raw-materials',
    newEntryRoute: '/gate/raw-materials/new',
    viewPermissions: [GATE_PERMISSIONS.RAW_MATERIAL.VIEW, GATE_PERMISSIONS.RAW_MATERIAL.VIEW_FULL],
    createPermissions: [GATE_PERMISSIONS.RAW_MATERIAL.CREATE, GATE_PERMISSIONS.RAW_MATERIAL.RECEIVE_PO],
    icon: Package,
    colorClassName: 'text-blue-600',
    keywords: ['purchase', 'po', 'packing', 'asset', 'material'],
  },
  {
    id: 'daily-needs',
    title: 'Daily Needs (Food/Consumables)',
    description: 'Food, consumables, and routine supply inward entries.',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/daily-needs',
    newEntryRoute: '/gate/daily-needs/new',
    viewPermissions: [GATE_PERMISSIONS.DAILY_NEEDS.VIEW, GATE_PERMISSIONS.DAILY_NEEDS.VIEW_FULL],
    createPermissions: [GATE_PERMISSIONS.DAILY_NEEDS.CREATE],
    icon: UtensilsCrossed,
    colorClassName: 'text-yellow-600',
    keywords: ['food', 'consumables', 'canteen', 'routine'],
  },
  {
    id: 'maintenance',
    title: 'Maintenance (Spare parts/Tools)',
    description: 'Maintenance spares, tools, and service material inward entries.',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/maintenance',
    newEntryRoute: '/gate/maintenance/new',
    viewPermissions: [GATE_PERMISSIONS.MAINTENANCE.VIEW, GATE_PERMISSIONS.MAINTENANCE.VIEW_FULL],
    createPermissions: [GATE_PERMISSIONS.MAINTENANCE.CREATE],
    icon: Wrench,
    colorClassName: 'text-purple-600',
    keywords: ['spare', 'tool', 'maintenance', 'service'],
  },
  {
    id: 'construction',
    title: 'Construction (Civil/Building Work)',
    description: 'Civil work, building material, and contractor construction arrivals.',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/construction',
    newEntryRoute: '/gate/construction/new',
    viewPermissions: [GATE_PERMISSIONS.CONSTRUCTION.VIEW, GATE_PERMISSIONS.CONSTRUCTION.VIEW_FULL],
    createPermissions: [GATE_PERMISSIONS.CONSTRUCTION.CREATE],
    icon: Building2,
    colorClassName: 'text-orange-600',
    keywords: ['civil', 'building', 'construction', 'contractor'],
  },
  {
    id: 'fixed-assets',
    title: 'Fixed Assets',
    description: 'Capital asset and equipment inward entries (machinery, tools, furniture).',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/fixed-assets',
    newEntryRoute: '/gate/fixed-assets/new',
    viewPermissions: [GATE_PERMISSIONS.FIXED_ASSET.VIEW],
    createPermissions: [GATE_PERMISSIONS.FIXED_ASSET.CREATE],
    icon: Boxes,
    colorClassName: 'text-teal-600',
    keywords: ['asset', 'fixed', 'capital', 'equipment', 'machinery'],
  },
  {
    id: 'visitor-labour',
    title: 'Visitor/Labour',
    description: 'Visitor, labour, contractor, and people movement entries.',
    direction: 'in',
    vehicleMode: 'non_vehicle',
    dashboardRoute: '/gate/visitor-labour',
    newEntryRoute: '/gate/visitor-labour/new',
    viewPermissions: [GATE_PERMISSIONS.PERSON_GATE_IN.VIEW],
    createPermissions: [GATE_PERMISSIONS.PERSON_GATE_IN.CREATE],
    icon: HardHat,
    colorClassName: 'text-red-600',
    keywords: ['visitor', 'labour', 'contractor', 'person'],
  },
  {
    id: 'labour-in',
    title: 'Labour In',
    description: 'Record how many labourers each contractor brought into each department.',
    direction: 'in',
    vehicleMode: 'non_vehicle',
    dashboardRoute: '/gate/labour-in',
    newEntryRoute: '/gate/labour-in',
    // Gate-person screen: gated on RECORD_IN only. LABOUR_GATE.VIEW is deliberately
    // excluded so an HOD (who holds VIEW to reach /labour) does NOT trip the Gate menu.
    viewPermissions: [GATE_PERMISSIONS.LABOUR_GATE.RECORD_IN],
    createPermissions: [GATE_PERMISSIONS.LABOUR_GATE.RECORD_IN],
    icon: UserPlus,
    colorClassName: 'text-red-600',
    keywords: ['labour', 'labor', 'contractor', 'department', 'headcount', 'count', 'mazdoor', 'in'],
  },
  {
    id: 'labour-out',
    title: 'Labour Out',
    description: 'Review labour-in counts department-wise and mark labour out as groups leave.',
    direction: 'out',
    vehicleMode: 'non_vehicle',
    dashboardRoute: '/gate/labour-out',
    newEntryRoute: '/gate/labour-out',
    // Gate-person screen: gated on RECORD_OUT only (see labour-in note above).
    viewPermissions: [GATE_PERMISSIONS.LABOUR_GATE.RECORD_OUT],
    createPermissions: [GATE_PERMISSIONS.LABOUR_GATE.RECORD_OUT],
    icon: UserMinus,
    colorClassName: 'text-blue-700',
    keywords: ['labour', 'labor', 'contractor', 'headcount', 'count', 'mazdoor', 'out'],
  },
  {
    id: 'empty-vehicle-in',
    title: 'Empty Vehicle In',
    description: 'Empty vehicle inward entries with reason and linked document.',
    direction: 'in',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/empty-vehicle-in',
    newEntryRoute: '/gate/empty-vehicle-in/new',
    viewPermissions: [GATE_PERMISSIONS.EMPTY_VEHICLE_IN.VIEW],
    createPermissions: [GATE_PERMISSIONS.EMPTY_VEHICLE_IN.CREATE],
    icon: LogIn,
    colorClassName: 'text-sky-700',
    keywords: ['empty', 'vehicle', 'bst', 'dispatch'],
  },
  {
    id: 'customer-return',
    title: 'Goods Return',
    description: 'Customer returned goods inward entries against SAP invoices.',
    direction: 'return',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/customer-return',
    newEntryRoute: '/gate/customer-return/new',
    viewPermissions: [GATE_PERMISSIONS.CUSTOMER_RETURN.VIEW],
    createPermissions: [GATE_PERMISSIONS.CUSTOMER_RETURN.CREATE],
    icon: Undo2,
    colorClassName: 'text-rose-700',
    keywords: ['goods return', 'customer', 'return', 'invoice', 'credit note', 'finished goods'],
  },
  {
    id: 'repair-parts-in',
    title: 'Repair Parts In',
    description: 'Receive repairable parts, tools, or maintenance items back.',
    direction: 'return',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/repair-parts-in',
    newEntryRoute: '/gate/repair-parts-in/new',
    viewPermissions: [GATE_PERMISSIONS.REPAIR_MOVEMENT.VIEW],
    createPermissions: [GATE_PERMISSIONS.REPAIR_MOVEMENT.CREATE],
    icon: RotateCcw,
    colorClassName: 'text-emerald-700',
    keywords: ['repair', 'parts', 'vendor', 'return'],
  },
  {
    id: 'rejected-qc-return',
    title: 'Rejected QC Return',
    description: 'Rejected inward material sent back out after QC or factory decision.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/rejected-qc-return',
    newEntryRoute: '/gate/rejected-qc-return/new',
    viewPermissions: [GATE_PERMISSIONS.REJECTED_QC_RETURN.VIEW],
    createPermissions: [GATE_PERMISSIONS.REJECTED_QC_RETURN.CREATE],
    icon: PackageX,
    colorClassName: 'text-rose-600',
    keywords: ['rejected', 'qc', 'return', 'factory head'],
    requiresWeighment: true,
    requiresGatepass: true,
  },
  {
    id: 'empty-vehicle-out',
    title: 'Empty Vehicle Out',
    description: 'Mark inward vehicles out when they leave without outbound goods.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/empty-vehicle-out',
    newEntryRoute: '/gate/empty-vehicle-out/new',
    viewPermissions: [GATE_PERMISSIONS.EMPTY_VEHICLE_OUT.VIEW],
    createPermissions: [GATE_PERMISSIONS.EMPTY_VEHICLE_OUT.CREATE],
    icon: LogOut,
    colorClassName: 'text-blue-700',
    keywords: ['empty', 'vehicle', 'out'],
    requiresWeighment: true,
    requiresGatepass: true,
  },
  {
    id: 'sales-dispatch',
    title: 'Sales Dispatch Out',
    description: 'View Docking-created invoice dispatches and mark vehicles out.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/sales-dispatch',
    newEntryRoute: '/dispatch/docking/new',
    viewPermissions: [GATE_PERMISSIONS.SALES_DISPATCH.VIEW],
    createPermissions: [],
    icon: Send,
    colorClassName: 'text-blue-600',
    keywords: ['sales dispatch out', 'docking', 'sales', 'dispatch', 'customer', 'delivery', 'invoice', 'gate out'],
    requiresWeighment: true,
    requiresGatepass: true,
  },
  {
    id: 'bst-out',
    title: 'BST Out (Branch Transfer)',
    description: 'Branch stock transfers approved by the warehouse, awaiting vehicle gate-out.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/bst-out',
    newEntryRoute: '/gate/bst-out',
    viewPermissions: [GATE_PERMISSIONS.BST_OUT.VIEW],
    createPermissions: [],
    icon: Truck,
    colorClassName: 'text-amber-600',
    keywords: ['bst', 'branch', 'stock transfer', 'warehouse', 'gate out', 'dispatch', 'transfer'],
    requiresGatepass: true,
  },
  {
    id: 'repair-parts-out',
    title: 'Repair Parts Out',
    description: 'Send repairable spare parts, tools, or maintenance items to vendors.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/repair-parts-out',
    newEntryRoute: '/gate/repair-parts-out/new',
    viewPermissions: [GATE_PERMISSIONS.REPAIR_MOVEMENT.VIEW],
    createPermissions: [GATE_PERMISSIONS.REPAIR_MOVEMENT.CREATE],
    icon: Wrench,
    colorClassName: 'text-slate-600',
    keywords: ['repair', 'parts', 'vendor', 'out'],
    requiresGatepass: true,
  },
  {
    // The gate-side halves of the Returnable Gate Pass. The document itself is
    // raised and closed by a department; the gate only records the movement.
    id: 'returnable-out',
    title: 'Returnable Out',
    description: 'Approved returnable gate passes waiting to leave for repair, exchange or job work.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/return-out',
    newEntryRoute: '/gate/return-out',
    viewPermissions: [GATE_PERMISSIONS.RETURNABLE.GATE_OUT],
    createPermissions: [GATE_PERMISSIONS.RETURNABLE.GATE_OUT],
    icon: PackageOpen,
    colorClassName: 'text-indigo-600',
    keywords: ['returnable', 'rgp', 'gate pass', 'repair', 'exchange', 'out'],
    hideFromNewEntry: true,
  },
  {
    id: 'returnable-in',
    title: 'Returnable In',
    description: 'Material out with a party, coming back against a returnable gate pass.',
    direction: 'return',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/return-in',
    newEntryRoute: '/gate/return-in',
    viewPermissions: [GATE_PERMISSIONS.RETURNABLE.GATE_IN],
    createPermissions: [GATE_PERMISSIONS.RETURNABLE.GATE_IN],
    icon: Undo2,
    colorClassName: 'text-indigo-700',
    keywords: ['returnable', 'rgp', 'gate pass', 'return', 'back', 'overdue', 'in'],
    hideFromNewEntry: true,
  },
  {
    id: 'job-work',
    title: 'Job Work / Oil Refining',
    description: 'Oil refining vehicle movement with production order linking later.',
    direction: 'out',
    vehicleMode: 'vehicle',
    dashboardRoute: '/gate/job-work',
    newEntryRoute: '/gate/job-work/new',
    viewPermissions: [GATE_PERMISSIONS.DASHBOARD.VIEW, GATE_PERMISSIONS.JOB_WORK.VIEW],
    createPermissions: [GATE_PERMISSIONS.JOB_WORK.CREATE],
    icon: Factory,
    colorClassName: 'text-cyan-600',
    keywords: ['job work', 'oil refining', 'production order', 'crude'],
    requiresWeighment: true,
  },
];

export const GATE_ENTRY_CREATE_PERMISSIONS = Array.from(
  new Set(GATE_ENTRY_TYPES.flatMap((entryType) => entryType.createPermissions)),
);

export const GATE_ENTRY_VIEW_PERMISSIONS = Array.from(
  new Set(GATE_ENTRY_TYPES.flatMap((entryType) => entryType.viewPermissions)),
);

export function findGateEntryType(entryTypeId: string | undefined) {
  return GATE_ENTRY_TYPES.find((entryType) => entryType.id === entryTypeId);
}
